Remove assumptions about preprocessor_next
binpash/hs pull request #12
Opened 2023-03-05 06:58 UTC by AnirudhNarsipur

Slight changes to the prototype that remove making any assumptions about the preprocessor (previously it was assumed there were no false negatives).

2023-03-06 23:51 UTC, sidprasad commented on model-checking/scheduler.als
> +
nit: Remove

2023-03-07 21:21 UTC, sidprasad requested changes

2023-03-07 21:21 UTC, sidprasad commented on model-checking/scheduler.als
> +        //TODO: shouldn't we have to specify something here?
I think this is the key situation (and is tricky)

If there is a dependency, you need to add it to preprocessor_next, but also remove any dependencies from preprocessor_next that would violate partialOrder

2023-03-07 21:21 UTC, sidprasad commented on model-checking/scheduler.als
> +    pred nonCommittedDep[c : Command]
What should this predicate be used for? I don't see it currently referenced

2023-03-07 21:21 UTC, sidprasad commented on model-checking/scheduler.als
> +
Can you help me understand the intent here :) Comments may be useful

2023-03-07 21:21 UTC, sidprasad commented on model-checking/scheduler.als
> +
I may be misunderstanding, but this doesn't seem like a property of wellFormed-ness

2023-03-08 13:47 UTC, sidprasad commented on model-checking/scheduler.als
> +            (x->y in r) implies no (((y.^r)->x) & r) // Transitivity
This is not transitivity. What's the intended change here?

This predicate no longer represents a partial order (it's over constrained)

2023-03-09 19:19 UTC, AnirudhNarsipur commented
Newest Commits should have a working model of variable preproc. 

See inline comments.

2023-03-09 19:30 UTC, sidprasad commented on model-checking/scheduler.als
> +}  for exactly 4 State , 6 Command
nit: phrase this to be a valid check or run

2023-03-09 19:31 UTC, sidprasad approved these changes

2023-03-09 21:12 UTC, merged